#
# Replaces the classic BotBuilder-DotNet-master-CI-PR-(MacLinux)
#

# "name" here defines the build number format. Build number is accessed via $(Build.BuildNumber)
name: $(Build.BuildId)

pool:
    vmImage: 'windows-2019'

trigger: none # ci trigger is set in ADO
pr: none # pr trigger is set in ADO

variables:
  BuildConfiguration: debug
steps:
# Note: Template ci-build-steps.yml is not supported in macOS because it calls VSBuild@1 in order to build the Windows-only ASP.NET Desktop assemblies.

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet '

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'Bots\DotNet\FunctionalTestsBots.sln'
    feedsToUse: 'select'
    

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: Bots\DotNet\FunctionalTestsBots.sln


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: build folder'
  inputs:
    PathtoPublish: build
    ArtifactName: build

- powershell: |
   cd ..
   ls -R
  displayName: 'Dir workspace'
  continueOnError: true
  condition: succeededOrFailed()
